/*
 * This file is generated by jOOQ.
 */
package ru.rusile.`social-network`.jooq


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", ru.rusile.`social-network`.jooq.DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.users</code>.
     */
    val USERS: ru.rusile.`social-network`.jooq.tables.Users get() = ru.rusile.`social-network`.jooq.tables.Users.USERS

    override fun getCatalog(): Catalog = ru.rusile.`social-network`.jooq.DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        ru.rusile.`social-network`.jooq.tables.Users.USERS
    )
}
