/*
 * This file is generated by jOOQ.
 */
package ru.rusile.`social-network`.jooq.tables.records


import java.time.LocalDate

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersRecord() : TableRecordImpl<UsersRecord>(ru.rusile.`social-network`.jooq.tables.Users.USERS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var surname: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var birthDate: LocalDate?
        set(value): Unit = set(3, value)
        get(): LocalDate? = get(3) as LocalDate?

    open var city: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: Long? = null, surname: String? = null, name: String? = null, birthDate: LocalDate? = null, city: String? = null): this() {
        this.id = id
        this.surname = surname
        this.name = name
        this.birthDate = birthDate
        this.city = city
        resetChangedOnNotNull()
    }
}
