/*
 * This file is generated by jOOQ.
 */
package ru.rusile.socialnetwork.jooq.tables.records


import java.time.LocalDate
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import ru.rusile.socialnetwork.jooq.tables.Users


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersRecord() : UpdatableRecordImpl<UsersRecord>(Users.USERS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var surname: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var birthDate: LocalDate?
        set(value): Unit = set(3, value)
        get(): LocalDate? = get(3) as LocalDate?

    open var city: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var biography: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: UUID? = null, surname: String? = null, name: String? = null, birthDate: LocalDate? = null, city: String? = null, biography: String? = null): this() {
        this.id = id
        this.surname = surname
        this.name = name
        this.birthDate = birthDate
        this.city = city
        this.biography = biography
        resetChangedOnNotNull()
    }
}
