/*
 * This file is generated by jOOQ.
 */
package ru.rusile.socialnetwork.jooq.tables.records


import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import ru.rusile.socialnetwork.jooq.tables.UserCreds


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserCredsRecord() : UpdatableRecordImpl<UserCredsRecord>(UserCreds.USER_CREDS) {

    open var userId: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var passwordHash: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised UserCredsRecord
     */
    constructor(userId: UUID? = null, passwordHash: String? = null): this() {
        this.userId = userId
        this.passwordHash = passwordHash
        resetChangedOnNotNull()
    }
}
