/*
 * This file is generated by jOOQ.
 */
package ru.rusile.socialnetwork.jooq.keys


import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

import ru.rusile.socialnetwork.jooq.tables.UserCreds
import ru.rusile.socialnetwork.jooq.tables.Users
import ru.rusile.socialnetwork.jooq.tables.records.UserCredsRecord
import ru.rusile.socialnetwork.jooq.tables.records.UsersRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val USER_CREDS_PKEY: UniqueKey<UserCredsRecord> = Internal.createUniqueKey(UserCreds.USER_CREDS, DSL.name("user_creds_pkey"), arrayOf(UserCreds.USER_CREDS.USER_ID), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), arrayOf(Users.USERS.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val USER_CREDS__USER_CREDS_USER_ID_FKEY: ForeignKey<UserCredsRecord, UsersRecord> = Internal.createForeignKey(UserCreds.USER_CREDS, DSL.name("user_creds_user_id_fkey"), arrayOf(UserCreds.USER_CREDS.USER_ID), ru.rusile.socialnetwork.jooq.keys.USERS_PKEY, arrayOf(Users.USERS.ID), true)
