/*
 * This file is generated by jOOQ.
 */
package ru.rusile.`social-network`.jooq.tables.references




/**
 * The table <code>public.users</code>.
 */
val USERS: ru.rusile.`social-network`.jooq.tables.Users = ru.rusile.`social-network`.jooq.tables.Users.USERS
