CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    surname VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    city VARCHAR(255) NOT NULL,
    biography VARCHAR(511)
);

CREATE TABLE IF NOT EXISTS user_creds (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    password_hash VARCHAR(255) NOT NULL
);