/*
 * This file is generated by jOOQ.
 */
package ru.rusile.`social-network`.jooq.tables


import java.time.LocalDate

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Users(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ru.rusile.`social-network`.jooq.tables.records.UsersRecord>?,
    parentPath: InverseForeignKey<out Record, ru.rusile.`social-network`.jooq.tables.records.UsersRecord>?,
    aliased: Table<ru.rusile.`social-network`.jooq.tables.records.UsersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ru.rusile.`social-network`.jooq.tables.records.UsersRecord>(
    alias,
    ru.rusile.`social-network`.jooq.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.users</code>
         */
        val USERS: Users = Users()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ru.rusile.`social-network`.jooq.tables.records.UsersRecord> = ru.rusile.`social-network`.jooq.tables.records.UsersRecord::class.java

    /**
     * The column <code>public.users.id</code>.
     */
    val ID: TableField<ru.rusile.`social-network`.jooq.tables.records.UsersRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.users.surname</code>.
     */
    val SURNAME: TableField<ru.rusile.`social-network`.jooq.tables.records.UsersRecord, String?> = createField(DSL.name("surname"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.users.name</code>.
     */
    val NAME: TableField<ru.rusile.`social-network`.jooq.tables.records.UsersRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.users.birth_date</code>.
     */
    val BIRTH_DATE: TableField<ru.rusile.`social-network`.jooq.tables.records.UsersRecord, LocalDate?> = createField(DSL.name("birth_date"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>public.users.city</code>.
     */
    val CITY: TableField<ru.rusile.`social-network`.jooq.tables.records.UsersRecord, String?> = createField(DSL.name("city"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<ru.rusile.`social-network`.jooq.tables.records.UsersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ru.rusile.`social-network`.jooq.tables.records.UsersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ru.rusile.`social-network`.jooq.tables.records.UsersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.users</code> table reference
     */
    constructor(): this(DSL.name("users"), null)
    override fun getSchema(): Schema? = if (aliased()) null else ru.rusile.`social-network`.jooq.Public.PUBLIC
    override fun getIdentity(): Identity<ru.rusile.`social-network`.jooq.tables.records.UsersRecord, Long?> = super.getIdentity() as Identity<ru.rusile.`social-network`.jooq.tables.records.UsersRecord, Long?>
    override fun `as`(alias: String): Users = Users(DSL.name(alias), this)
    override fun `as`(alias: Name): Users = Users(alias, this)
    override fun `as`(alias: Table<*>): Users = Users(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Users = Users(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Users = Users(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Users = Users(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Users = Users(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Users = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Users = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Users = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Users = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Users = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Users = where(DSL.notExists(select))
}
