/*
 * This file is generated by jOOQ.
 */
package ru.rusile.socialnetwork.jooq.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import ru.rusile.socialnetwork.jooq.Public
import ru.rusile.socialnetwork.jooq.keys.USER_CREDS_PKEY
import ru.rusile.socialnetwork.jooq.keys.USER_CREDS__USER_CREDS_USER_ID_FKEY
import ru.rusile.socialnetwork.jooq.tables.Users.UsersPath
import ru.rusile.socialnetwork.jooq.tables.records.UserCredsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserCreds(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserCredsRecord>?,
    parentPath: InverseForeignKey<out Record, UserCredsRecord>?,
    aliased: Table<UserCredsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserCredsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.user_creds</code>
         */
        val USER_CREDS: UserCreds = UserCreds()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserCredsRecord> = UserCredsRecord::class.java

    /**
     * The column <code>public.user_creds.user_id</code>.
     */
    val USER_ID: TableField<UserCredsRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.user_creds.password_hash</code>.
     */
    val PASSWORD_HASH: TableField<UserCredsRecord, String?> = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserCredsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserCredsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserCredsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.user_creds</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_creds</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_creds</code> table reference
     */
    constructor(): this(DSL.name("user_creds"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserCredsRecord>?, parentPath: InverseForeignKey<out Record, UserCredsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USER_CREDS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UserCredsPath : UserCreds, Path<UserCredsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserCredsRecord>?, parentPath: InverseForeignKey<out Record, UserCredsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UserCredsRecord>): super(alias, aliased)
        override fun `as`(alias: String): UserCredsPath = UserCredsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UserCredsPath = UserCredsPath(alias, this)
        override fun `as`(alias: Table<*>): UserCredsPath = UserCredsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<UserCredsRecord> = USER_CREDS_PKEY
    override fun getReferences(): List<ForeignKey<UserCredsRecord, *>> = listOf(USER_CREDS__USER_CREDS_USER_ID_FKEY)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, USER_CREDS__USER_CREDS_USER_ID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): UserCreds = UserCreds(DSL.name(alias), this)
    override fun `as`(alias: Name): UserCreds = UserCreds(alias, this)
    override fun `as`(alias: Table<*>): UserCreds = UserCreds(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserCreds = UserCreds(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserCreds = UserCreds(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserCreds = UserCreds(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UserCreds = UserCreds(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UserCreds = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UserCreds = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UserCreds = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UserCreds = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UserCreds = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserCreds = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserCreds = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UserCreds = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UserCreds = where(DSL.notExists(select))
}
